---
title: "Beta Diversities"
output:
  html_document:
    toc: true
---

Jensen-Shannon Divergence
=========================

Jensen-Shannon Divergence for comparing pairs of microbial communities: If P and Q are rwo discrete propability distributions then Kullbach - Leibler divergence is

$$D_{kl}(P||Q) = \sum_i P(i) log \frac{P(i)}{Q(i)}   $$
and the Jensen Shannon Divergence is
$$JSD(P||Q) = \frac{1}{2}D(P||M) + \frac{1}{2}D(P||M)    $$ where
$$ M = \frac{1}{2} (P+Q)$$

vegan::vegdist() distances
==========================

The following distances are calculated through package vegan. Copying from `?vegdist()`:

The following overview gives first the quantitative version, where x[ij] x[ik] refer to the quantity on species (column) i and sites (rows) j and k. In binary versions A and B are the numbers of species on compared sites, and J is the number of species that occur on both compared sites similarly.


1. euclidean	$$ d[jk] = \sqrt(\sum(x[ij]-x[ik])^2) $$
    + binary version: $$\sqrt(A+B-2*J) $$


2. manhattan	$$d[jk] = \sum( |{(x[ij] - x[ik])}|)$$
   + binary version: $$A+B-2*J$$


3. gower	$$d[jk] = (1/M) \sum|\frac{((x[ij]-x[ik])}{(max(x[i])-min(x[i])))}|$$

   + binary version: $$\frac{(A+B-2*J)}{M},$$ where M is the number of columns (excluding missing values)


4. altGower	$$d[jk] = \frac{1}{NZ} \sum |x[ij] - x[ik]|$$
where NZ is the number of non-zero columns excluding double-zeros (Anderson et al. 2006).
 + binary version: $$\frac{(A+B-2*J)}{(A+B-J)}$$

5. canberra	$$d[jk] = \frac{1}{NZ} \sum \frac{|x[ij]-x[ik]|}{|x[ij]|+ |x[ik]|}$$
where NZ is the number of non-zero entries.
 + binary version: $$\frac{A+B-2*J}{A+B-J}$$


6. bray	$$d[jk] = \frac {\sum |x[ij]-x[ik]|}{\sum x[ij]+x[ik]}$$
  + binary version: $$\frac{A+B-2*J}{A+B} $$

7. kulczynski $$	d[jk]= 1 - 0.5*[\sum \frac {min(x[ij],x[ik])}{sum x[ij]} + \sum \frac {min(x[ij],x[ik])}{sum x[ik]}] $$
 + binary version: $$ 1- \frac {\frac{J}{A} + \frac{J}{B}}{2} $$

8. morisita : $$	d[jk] = 1 - 2*\sum \frac{(x[ij]*x[ik])}{lambda[j]+lambda[k]} * \sum(x[ij])*\sum(x[ik])) $$ 
where
$$ lambda[j] = \frac {\sum(x[ij]*(x[ij]-1))}{\sum(x[ij])*\sum(x[ij]-1)} $$
 + binary version: Is not applicable

9. Horn : Is like morisita, but $$lambda[j] = frac{\sum(x[ij]^2)}{(\sum(x[ij])^2)}$$
 + binary version: $$ \frac {(A+B-2*J)}{(A+B)} $$

10. binomial :	$$ d[jk] = \sum(x[ij]*log( \frac{x[ij]}{n[i]}) + x[ik]*log(\frac {x[ik]}{n[i]}) - n[i]*\frac{log(\frac{1}{2})}{n[i]} $$,
where $$n[i] = x[ij] + x[ik]$$
 + binary version: $$ log(2)*(A+B-2*J)$$

11. cao :  $$	d[jk] = (1/S) * \sum(log(\frac{n[i]}{2}) - (x[ij]*log(x[ik]) + x[ik]*log(\frac{x[ij]))}{n[i]}) $$,
where S is the number of species in compared sites and n[i] = x[ij] + x[ik]

12. jaccard Index : $$ \frac {2B}{(1+B)} $$ , where B is Bray–Curtis dissimilarity.

13. mountford : Is $$ M = \frac{1}{a}$$ where α is the parameter of Fisher's logseries assuming that the compared communities are samples from the same community.  Index M is found as the positive root of equation $$ exp(a*M) + exp(b*M) = 1 + exp((a+b-j)*M) $$,
where j is the number of species occurring in both communities, and a and b are the number of species in each separate community

14. Raup: Raup–Crick dissimilarity  is a probabilistic index based on presence/absence data. It is defined as 1 - prob(j), or based on the probability of observing at least j species in shared in compared communities. See vegdist() for details.

15. Chao:  A Jaccard type index defined as
$$d[jk] = 1 - U[j]*U[k]/(U[j] + U[k] - U[j]*U[k])$$ where
$$U[j] = \frac{C[j]}{N[j]} + \frac {(N[k] -1)}{N[k]} * \frac{a1}{(2*a2)} * \frac {S[j]}{N[j]}$$
and similarly for U[k]. Here C[j] is the total number of individuals in the species of site j that are shared with site k, N[j] is the total number of individuals at site j, a1 (and a2) are the number of species occurring in site j that have only one (or two) individuals in site k, and S[j] is the total number of individuals in the species present at site j that occur with only one individual in site k.


vegan::betadiver() Indices
==========================

The following Indices are from `vegan::betadiver()`. They use the following notation:

> "Component a comprises the total number of species that occur in both quadrats, component b comprises the total number of species that occur in the neighbouring quadrat but not in the focal one, component c comprises the total number of species that occur in the focal quadrat but not in the neighbouring one." The previous definition comes from "Measuring beta diversity for presence–absence data" (Koleff,Gaston & Lannon,2013)


1. "w" :$$  \frac {b+c}{2*a+b+c}$$
2. "-1" $$ \frac{(b+c)}{(2*a+b+c)}$$
3.  "c" = $$\frac{(b+c)}{2}$$
4. "wb" = $$ b+c $$
5. "r" = $$ \frac{2*b*c}{((a+b+c)^2-2*b*c)} $$
6. "I" = $$log(2*a+b+c) - \frac{2*a*log(2)}{(2*a+b+c)} - ((a+b)*log(a+b) + \frac       {(a+c)*log(a+c)} {(2*a+b+c)}) $$
7. "e" = $$ e^{(log(2*a+b+c)} - 2*a*\frac{log(2)}{(2*a+b+c)} - (\frac{(a+b)*log(a+b) + (a+c)*log(a+c))}
{(2*a+b+c))}-1 $$
8. "t" =  $$\frac{(b+c)}{(2*a+b+c)} $$
9. "me" = $$ \frac {(b+c)}{(2*a+b+c)} $$
10. "j" = $$ \frac{a}{(a+b+c)} $$
11. "sor" =  $$ \frac {2*a}{(2*a+b+c)}$$
12. "m" =  $$\frac {(2*a+b+c)*(b+c)}{(a+b+c)} $$
13. "-2" = $$ \frac {pmin(b,c)}{(pmax(b,c)+a)} $$
14. "co" =$$ \frac {(a*c+a*b+2*b*c)}{(2*(a+b)*(a+c))} $$
15. "cc" = $$ \frac {(b+c)}{(a+b+c)} $$
16. "g" = $$\frac{(b+c)}{(a+b+c)}$$
17. "-3" = $$ \frac {pmin(b,c)}{(a+b+c)} $$
18. "l" = $$ \frac {(b+c)}{2} $$
19. "hk" = $$ \frac {(b+c)}{(2*a+b+c)} $$
20. "rlb" = $$\frac {a}{(a+c)} $$
21. "sim" = $$ \frac{pmin(b,c)}{(pmin(b,c)+a)}$$
22. "gl" = $$ \frac {2*abs(b-c)}{(2*a+b+c)}$$
23. "z" = $$\frac{(log(2)-log(2*a+b+c)+log(a+b+c))}{log(2)}$$


Distances from stats::distance
==============================

Rest of the distances come from stats::distance ().

1. maximum: Maximum distance between two components of x and y (supremum norm)

2. binary:: The vectors are regarded as binary bits, so non-zero elements are ‘on’ and zero elements are ‘off’. The distance is the proportion of bits in which only one is on amongst those in which at least one is on.

3. minkowski:The p norm, the pth root of the sum of the pth powers of the differences of the components.


**References**

Anderson, M.J., Ellingsen, K.E. & McArdle, B.H. (2006) , "Multivariate dispersion as a measure of beta diversity". Ecology Letters 9, 683–693.

Bent Fuglede and Flemming Topsoe (2004), "Jensen-Shannon Divergence and Hilbert space embedding." International Symposium on Information Theory, 2004. ISIT 2004,  DOI: 10.1109/ISIT.2004.1365067

Patricia Koleff,Kevin J. Gaston and Jack J. Lennon (2003), "Measuring beta diversity for presence–absence data", Animal Ecology Volume 72, Issue 3 , DOI: 10.1046/j.1365-2656.2003.00710.x
